from __future__ import annotations


SETTLEMENT_CONFIG_METADATA = {
    "sections": [
        {
            "key": "tax_rates",
            "title": "세율",
            "description": "정산 산출에 적용되는 세금율입니다.",
            "fields": [
                {
                    "key": "income_tax_rate",
                    "label": "소득세율",
                    "description": "과세 기준 소득세율",
                    "input_type": "percent",
                    "unit": "%",
                    "min": "0.0000",
                    "max": "100.0000",
                    "decimal_precision": 4,
                    "required": True,
                },
                {
                    "key": "vat_tax_rate",
                    "label": "부가가치세율",
                    "description": "부가세 적용율",
                    "input_type": "percent",
                    "unit": "%",
                    "min": "0.0000",
                    "max": "100.0000",
                    "decimal_precision": 4,
                    "required": True,
                },
            ],
        },
        {
            "key": "reported_amount",
            "title": "정산 반영 기준",
            "description": "보고 금액 반영 및 산정 보정 계수입니다.",
            "fields": [
                {
                    "key": "reported_amount_rate",
                    "label": "보고 금액 반영률",
                    "description": "정산에서 반영되는 보고 금액의 비율",
                    "input_type": "percent",
                    "unit": "%",
                    "min": "0.0000",
                    "max": "100.0000",
                    "decimal_precision": 4,
                    "required": True,
                },
            ],
        },
        {
            "key": "insurance_rates",
            "title": "보험료율",
            "description": "4대 보험 및 산재/고용 관련 보험율입니다.",
            "fields": [
                {
                    "key": "national_pension_rate",
                    "label": "국민연금 보험료율",
                    "description": "국민연금 부담률",
                    "input_type": "percent",
                    "unit": "%",
                    "min": "0.0000",
                    "max": "100.0000",
                    "decimal_precision": 4,
                    "required": True,
                },
                {
                    "key": "health_insurance_rate",
                    "label": "건강보험 보험료율",
                    "description": "건강보험 부담률",
                    "input_type": "percent",
                    "unit": "%",
                    "min": "0.0000",
                    "max": "100.0000",
                    "decimal_precision": 4,
                    "required": True,
                },
                {
                    "key": "medical_insurance_rate",
                    "label": "장기요양보험료율",
                    "description": "건강보험료 기반 장기요양보험율",
                    "input_type": "percent",
                    "unit": "%",
                    "min": "0.0000",
                    "max": "100.0000",
                    "decimal_precision": 4,
                    "required": True,
                },
                {
                    "key": "employment_insurance_rate",
                    "label": "고용보험 보험료율",
                    "description": "고용보험 부담률",
                    "input_type": "percent",
                    "unit": "%",
                    "min": "0.0000",
                    "max": "100.0000",
                    "decimal_precision": 4,
                    "required": True,
                },
                {
                    "key": "industrial_accident_insurance_rate",
                    "label": "산재보험 보험료율",
                    "description": "산업재해보상보험 부담률",
                    "input_type": "percent",
                    "unit": "%",
                    "min": "0.0000",
                    "max": "100.0000",
                    "decimal_precision": 4,
                    "required": True,
                },
                {
                    "key": "special_employment_insurance_rate",
                    "label": "특별고용보험 보험료율",
                    "description": "특별고용보험 부담률",
                    "input_type": "percent",
                    "unit": "%",
                    "min": "0.0000",
                    "max": "100.0000",
                    "decimal_precision": 4,
                    "required": True,
                },
                {
                    "key": "special_industrial_accident_insurance_rate",
                    "label": "특별산재보험 보험료율",
                    "description": "특별산재보험 부담률",
                    "input_type": "percent",
                    "unit": "%",
                    "min": "0.0000",
                    "max": "100.0000",
                    "decimal_precision": 4,
                    "required": True,
                },
            ],
        },
        {
            "key": "thresholds",
            "title": "기타 기준",
            "description": "정산 하한선 및 수고비 기준입니다.",
            "fields": [
                {
                    "key": "two_insurance_min_settlement_amount",
                    "label": "2대 보험 최소 정산금액",
                    "description": "2대 보험 산정의 하한 정산 금액",
                    "input_type": "currency",
                    "unit": "원",
                    "min": "0.00",
                    "max": "1000000.00",
                    "integer_only": True,
                    "required": True,
                },
                {
                    "key": "meal_allowance",
                    "label": "식비",
                    "description": "운영 기본 식비 기준",
                    "input_type": "currency",
                    "unit": "원",
                    "min": "0.00",
                    "max": "1000000.00",
                    "integer_only": True,
                    "required": True,
                },
            ],
        },
    ]
}
