# Generated by Django 5.1.15 on 2026-03-24 03:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SettlementPolicy",
            fields=[
                (
                    "policy_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("policy_code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("policy_id",),
            },
        ),
        migrations.CreateModel(
            name="SettlementPolicyVersion",
            fields=[
                (
                    "policy_version_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("rule_payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("published", "published"),
                            ("retired", "retired"),
                        ],
                        max_length=32,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "policy",
                    models.ForeignKey(
                        db_column="policy_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="settlementregistry.settlementpolicy",
                    ),
                ),
            ],
            options={
                "ordering": ("policy_version_id",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy", "version_number"),
                        name="unique_policy_version_number_per_policy",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SettlementPolicyAssignment",
            fields=[
                (
                    "assignment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField()),
                ("fleet_id", models.UUIDField()),
                ("effective_start_date", models.DateField()),
                ("effective_end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        max_length=32,
                    ),
                ),
                (
                    "policy_version",
                    models.ForeignKey(
                        db_column="policy_version_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="settlementregistry.settlementpolicyversion",
                    ),
                ),
            ],
            options={
                "ordering": ("assignment_id",),
            },
        ),
    ]
