# Generated by Django 5.1.15 on 2026-04-09 00:00

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("settlementregistry", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="GlobalSettlementConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("singleton_key", models.CharField(default="global", max_length=32, unique=True)),
                ("income_tax_rate", models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=8)),
                ("vat_tax_rate", models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=8)),
                (
                    "reported_amount_rate",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=8),
                ),
                (
                    "national_pension_rate",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=8),
                ),
                (
                    "health_insurance_rate",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=8),
                ),
                (
                    "medical_insurance_rate",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=8),
                ),
                (
                    "employment_insurance_rate",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=8),
                ),
                (
                    "industrial_accident_insurance_rate",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=8),
                ),
                (
                    "special_employment_insurance_rate",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=8),
                ),
                (
                    "special_industrial_accident_insurance_rate",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=8),
                ),
                (
                    "two_insurance_min_settlement_amount",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=12),
                ),
                ("meal_allowance", models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=12)),
            ],
        ),
    ]
